kind: pipeline
name: default

steps:
  - name: data-collector-cron-job
    image: plugins/gcr
    settings:
      dockerfile: Dockerfile
      repo: eu.gcr.io/prod-bip/data-collector-cron-job
      registry: eu.gcr.io
      tags:
        - latest
        - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}
      json_key:
        from_secret: gcr_credentials

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: bip-ci-test
    when:
      status: [ success, failure ]
    depends_on:
      - data-collector-cron-job

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url
---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials
---
kind: secret
name: gcs_credentials
get:
  path: drone-gcs-credentials
  name: gcs-credentials
